.github/workflows/cargo.yml, Cargo.lock, packages/jest/Cargo.toml, packages/styled-components/Cargo.toml, packages/styled-components/transforms/Cargo.toml, packages/styled-components/transforms/tests/fixtures/transpile-css-prop-add-import/output.js, packages/styled-components/transforms/tests/fixtures/transpile-css-prop-add-require/output.js, packages/styled-components/transforms/tests/fixtures/transpile-css-prop-all-options-on/output.js, packages/styled-components/transforms/tests/fixtures/transpile-css-prop/output.js
Please publish a new version after this is merged
=> chore(deps): update deps

.rustfmt.toml, Cargo.lock, packages/jest/Cargo.toml, packages/jest/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/src/lib.rs, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json
=> chore(deps): Update swc

packages/relay/package.json
=> fix(relay): fix wrong `package.json#types` field

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/jest/Cargo.toml, packages/jest/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json
- Closes https://github.com/swc-project/plugins/issues/60
- Closes https://github.com/swc-project/plugins/issues/69
This also closes
- Closes https://github.com/swc-project/plugins/issues/62
as this includes recent PR toward next.js
=> chore: Update swc

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/jest/Cargo.toml, packages/jest/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json
Closes https://github.com/swc-project/plugins/issues/71
=> fix: Workaround a bug of `rkyv`

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/.gitignore, packages/noop/Cargo.toml, packages/noop/package.json, packages/noop/src/lib.rs, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json
This plugin is for debugging purposes.
If this plugin crashes, it means that something is wrong with `@swc/core` or plugin api
=> feat(noop): Add a noop plugin

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/src/transform_css.rs, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json
PR bumps up swc_core to latest, along with fix some build errors.
=> build(cargo): bump up deps, fix build errors

Cargo.lock, Cargo.toml, crates/README.md, crates/tailwind/Cargo.toml, crates/tailwind/src/lib.rs, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
This PR is mainly to check if I selected correct structure
=> feat(tailwind): Initialize project

.github/workflows/bump-swc_core.yml
Trying to fix yaml syntax correctly.
=> ci(actions): fix bump swc_core action

Cargo.lock, crates/tailwind/Cargo.toml, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/tests/fixture/tpl-placeholder-2-as-part-of-value/output.js, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml, scripts/update-bump-all.sh
cc @kwonoj
I fixed the script
- Closes https://github.com/swc-project/plugins/pull/123
- Closes https://github.com/swc-project/plugins/pull/124
=> build(cargo): Update `swc_core` to `v0.48.12`

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/README.md, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/tests/fixture/styles/output.js, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
- Closes https://github.com/swc-project/plugins/issues/131
=> build(cargo): Update `swc_core` to `v0.52.8`

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/styled-components/package.json, packages/styled-components/src/lib.rs, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
- Closes https://github.com/swc-project/plugins/issues/136.
- Closes https://github.com/swc-project/plugins/issues/140.
=> fix(styled-components): Use stable hash

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
https://yarnpkg.com/configuration/manifest#preferUnplugged
=> chore: Set `preferUnplugged`

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/emotion/transform/src/lib.rs, packages/emotion/transform/tests/fixture.rs, packages/emotion/transform/tests/label-sanitisation/bad.const.name.js, packages/emotion/transform/tests/label-sanitisation/bad.const.name.ts, packages/emotion/transform/tests/label-sanitisation/bad.name.!#$%&()+,.;=@[]^`}~{.js, packages/emotion/transform/tests/label-sanitisation/bad.name.!#$%&()+,.;=@[]^`}~{.ts, packages/emotion/transform/tests/label-sanitisation/input.styles.js, packages/emotion/transform/tests/label-sanitisation/input.styles.ts, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
Pending #155 
This ports over the label sanitisation behaviour from emotin babel plugin, which sanitises the label input.
=> fix(emotion): Autolabel name sanitisation

Cargo.lock, package.json, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/relay/transform/Cargo.toml, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
Attempt to close https://github.com/swc-project/swc/issues/7255 .
=> build(cargo): Update `swc_core` to `v0.75.34`

Cargo.lock, packages/relay/Cargo.toml, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/src/transform_css_lightningcss.rs
Related PR: https://github.com/parcel-bundler/lightningcss/pull/574
=> refactor: Fix `Visitor` impls

.changeset/fast-roses-boil.md, Cargo.lock, packages/emotion/CHANGELOG.md, packages/emotion/README.md, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/emotion/transform/src/lib.rs, packages/emotion/transform/tests/fixture/issue-258/input.tsx, packages/emotion/transform/tests/fixture/issue-258/output.ts, scripts/bump.sh
=> fix(emotion): Fix regex for striping line comments out

.changeset/small-garlics-raise.md, Cargo.lock, packages/transform-imports/CHANGELOG.md, packages/transform-imports/README.md, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml, packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture/mapping-export/input.js, packages/transform-imports/transform/tests/fixture/mapping-export/output.js, packages/transform-imports/transform/tests/fixture/regex-export/input.js, packages/transform-imports/transform/tests/fixture/regex-export/output.js, packages/transform-imports/transform/tests/fixture/simple-export/input.js, packages/transform-imports/transform/tests/fixture/simple-export/output.js
=> feat(transform-imports): Transform exports

.changeset/eighty-hairs-dress.md, Cargo.lock, packages/styled-jsx/CHANGELOG.md, packages/styled-jsx/README.md, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/src/transform_css_lightningcss.rs, packages/styled-jsx/transform/src/transform_css_swc.rs, packages/styled-jsx/transform/tests/fixture/next-64389/input.js, packages/styled-jsx/transform/tests/fixture/next-64389/output.lightningcss.js, packages/styled-jsx/transform/tests/fixture/next-64389/output.swc.js, packages/styled-jsx/transform/tests/fixture/tpl-placeholder-1-as-property/output.lightningcss.js, packages/styled-jsx/transform/tests/fixture/tpl-placeholder-1-as-property/output.swc.js
- https://github.com/vercel/next.js/issues/64389
=> fix(styled-jsx): Fix interpolation

.changeset/beige-singers-whisper.md, Cargo.lock, packages/styled-components/CHANGELOG.md, packages/styled-components/README.md, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-components/transform/tests/fixtures/issue-289/code.js, packages/styled-components/transform/tests/fixtures/issue-289/config.json, packages/styled-components/transform/tests/fixtures/issue-289/output.js
=> test(styled-components): Add a test for a wrong issue

.changeset/orange-files-cover.md, Cargo.lock, packages/styled-components/CHANGELOG.md, packages/styled-components/README.md, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-components/transform/src/visitors/template_literals.rs, packages/styled-components/transform/tests/fixtures/annotate-create-global-style-with-pure-comments/output.js, packages/styled-components/transform/tests/fixtures/annotate-css-with-pure-comments/output.js, packages/styled-components/transform/tests/fixtures/annotate-keyframes-with-pure-comments/output.js, packages/styled-components/transform/tests/fixtures/annotate-styled-calls-with-pure-comments/output.js, packages/styled-components/transform/tests/fixtures/css-declared-after-component/output.js, packages/styled-components/transform/tests/fixtures/does-not-replace-native-with-no-tags/output.js, packages/styled-components/transform/tests/fixtures/ignore-external-styled-import/output.js, packages/styled-components/transform/tests/fixtures/issue-224/output.js, packages/styled-components/transform/tests/fixtures/issue-289/code.js, packages/styled-components/transform/tests/fixtures/issue-289/output.js, packages/styled-components/transform/tests/fixtures/minify-css-to-use-with-transpilation/output.js, packages/styled-components/transform/tests/fixtures/minify-css-to-use-without-transpilation/output.js, packages/styled-components/transform/tests/fixtures/minify-single-line-comments-with-interpolations/output.js, packages/styled-components/transform/tests/fixtures/next-59805/output.js, packages/styled-components/transform/tests/fixtures/transpile-css-prop-all-options-on/output.js, packages/styled-components/transform/tests/fixtures/transpile-require-default/output.js, packages/styled-components/transform/tests/fixtures/transpile-template-literals-with-config/output.js, packages/styled-components/transform/tests/fixtures/transpile-template-literals-without-config/output.js, packages/styled-components/transform/tests/fixtures/use-namespace/output.js
=> fix(styled-components): Remove wrong transpilation of tpl lits

.changeset/shiny-maps-applaud.md, packages/loadable-components/CHANGELOG.md, packages/loadable-components/README.md, packages/loadable-components/package.json, packages/loadable-components/src/lib.rs, packages/loadable-components/tests/fixture/simple import/with webpackChunkName comment/should use it even if quote is single/input.js, packages/loadable-components/tests/fixture/simple import/with webpackChunkName comment/should use it even if quote is single/output.js
=> fix(loadable-components): Allow using single quote

.changeset/kind-drinks-divide.md, packages/emotion/transform/src/lib.rs, packages/emotion/transform/tests/labels/emotion-js/css-inside-function.js, packages/emotion/transform/tests/labels/emotion-js/css-inside-function.ts, packages/emotion/transform/tests/labels/emotion-js/object-pattern-variable-declarator.js
This PR fixes https://github.com/swc-project/plugins/issues/303
We new fold children inside of ident expressions.
I've added an additional test case and also updated the critical extractions test that not notably was not performing transforms.
=> feat(emotion): Add support for css inside functions

.changeset/small-cars-count.md, Cargo.lock, packages/styled-jsx/CHANGELOG.md, packages/styled-jsx/README.md, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml
- **docs(changeset): Bump up lightningcss**
- **RELEASING: Releasing 1 package(s)**
- **Merge CHANGELOG into README**
- **Bump crates**
=> chore(styled-jsx): Publish changes

.changeset/serious-windows-call.md, Cargo.lock, packages/emotion/transform/tests/fixture.rs, packages/react-remove-properties/transform/tests/fixture.rs, packages/relay/CHANGELOG.md, packages/relay/README.md, packages/relay/package.json, packages/relay/transform/Cargo.toml, packages/relay/transform/src/lib.rs, packages/relay/transform/tests/fixture/simple/next-67614/input.js, packages/relay/transform/tests/fixture/simple/next-67614/output.js, packages/remove-console/transform/tests/fixture.rs, packages/styled-components/transform/tests/fixture.rs, packages/styled-jsx/transform/tests/fixture.rs, packages/transform-imports/transform/tests/fixture.rs
https://github.com/vercel/next.js/issues/67614
=> fix(relay): Handle comments in graphql

packages/formatjs/transform/src/lib.rs
=> fix(formatjs): Fix missing quotes of plural keys

crates/swc_icu_messageformat_parser/src/parser.rs, crates/swc_icu_messageformat_parser/tests/fixtures/unicode_1, crates/swc_icu_messageformat_parser/tests/run_parser_e2e.rs
=> fix(formatjs): Fix parsing of unicode

.changeset/perfect-vans-grab.md, packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture.rs, packages/transform-imports/transform/tests/fixture/dynamic-imports/input.js, packages/transform-imports/transform/tests/fixture/dynamic-imports/output.js
=> feat: Support dynamic imports from `transform-imports` plugin

.gitignore, package.json, packages/emotion/__tests__/__snapshots__/wasm.test.ts.snap, packages/emotion/__tests__/fixtures/input.js, packages/emotion/__tests__/wasm.test.ts, packages/emotion/package.json, packages/formatjs/__tests__/wasm.test.ts, packages/jest/__tests__/wasm.test.ts, packages/loadable-components/__tests__/wasm.test.ts, packages/prefresh/__tests__/wasm.test.ts, packages/react-remove-properties/__tests__/__snapshots__/wasm.test.ts.snap, packages/react-remove-properties/__tests__/wasm.test.ts, packages/relay/__tests__/__snapshots__/wasm.test.ts.snap, packages/relay/__tests__/wasm.test.ts, packages/remove-console/__test__/__snapshots__/wasm.test.ts.snap, packages/remove-console/__test__/fixtures/input.js, packages/remove-console/__test__/wasm.test.ts, packages/styled-components/__tests__/__snapshots__/wasm.test.ts.snap, packages/styled-components/__tests__/wasm.test.ts, packages/styled-jsx/__tests__/__snapshots__/wasm.test.ts.snap, packages/styled-jsx/__tests__/wasm.test.ts, packages/swc-confidential/__tests__/__snapshots__/wasm.test.ts.snap, packages/swc-confidential/__tests__/wasm.test.ts, packages/transform-imports/__tests__/__snapshots__/wasm.test.ts.snap, packages/transform-imports/__tests__/wasm.test.ts, pnpm-lock.yaml
Add WASM plugin test to ensure current @swc/core can load and run wasm plugin corrently.
=> test: add WASM plugin tests and snapshots for emotion, relay, and remove-console

.github/workflows/npm-publish.yml, package.json, packages/emotion/package.json, packages/formatjs/package.json, packages/jest/package.json, packages/loadable-components/package.json, packages/prefresh/package.json, packages/react-remove-properties/package.json, packages/relay/package.json, packages/remove-console/package.json, packages/styled-components/package.json, packages/styled-jsx/package.json, packages/swc-confidential/package.json, packages/transform-imports/package.json
- Run test before npm publish
- Test package in cargo debug build.
=> chore: Update npm scripts for prepack and test

.github/workflows/npm-publish.yml, package.json, packages/emotion/package.json, packages/formatjs/package.json, packages/jest/package.json, packages/loadable-components/package.json, packages/prefresh/package.json, packages/react-remove-properties/package.json, packages/relay/package.json, packages/remove-console/package.json, packages/styled-components/package.json, packages/styled-jsx/package.json, packages/swc-confidential/package.json, packages/transform-imports/package.json
- Run test before npm publish
- Test package in cargo debug build.
=> chore: add test when npm package prepack 

.changeset/tired-streets-grab.md, packages/formatjs/CHANGELOG.md, packages/formatjs/README.md, packages/formatjs/package.json
Releases:
@swc/plugin-formatjs@3.2.0
=> RELEASING: Releasing 1 package(s)
