swc-project/plugins

Cargo.lock, Cargo.toml, packages/relay/Cargo.toml, packages/relay/src/lib.rs
This is naive 1:1 port for the relay plugin in next-swc (https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/core/src/relay.rs)
next-swc does not split relay into separate package yet, so I took shortcut to copy-paste code in here first, the trying to refactor upstream if this plugin is suffecient to be used externally. 
Code is pretty much copy-paste. Only difference is plugin side config, and locating root via `/cwd` alias in wasi target.
=> feat(relay): initial relay plugin port

Cargo.lock, packages/jest/Cargo.toml, packages/relay/Cargo.toml, packages/relay/package.json, packages/relay/src/lib.rs, packages/styled-components/Cargo.toml, packages/styled-jsx/Cargo.toml
Partially related to https://github.com/swc-project/plugins/issues/35.
PR fixes 2 things
- first, using `swc_common::HANDLER` causes tls access error since it tries to use native host one. use plugin's pseudoscoped key instead.
- secondly, allow to pass `rootDir` instead of manually expand from env::current_dir or /cwd. I was incorrect to expect `PathBuf::from('/cwd')` expands to actual root path. It is not, instead it only gives to fs access to cwd _with mounted virtual path_. We can't use both, instead ask to host passes it.
Closes #35
=> fix(relay): avoid handler tls crash, allow rootdir config

README.md, packages/relay/README.md, packages/styled-components/README.md
Took me a minute to figure out all of the various pieces of this to [setup in our app](https://github.com/artsy/force/pull/10598) so figured I would come back and add some light docs.
=> feat(docs): Add light documentation for Relay and Styled Components

packages/emotion/README.md
- Fix emotion plugin code example to use the correct name
=> fix(emotion-plugin): change to right plugin name in code example

Cargo.lock, packages/jest/Cargo.toml, packages/jest/src/lib.rs, packages/relay/Cargo.toml, packages/relay/src/lib.rs
Use swc_core where available. Some plugins relying on external pkg (i.e emotion) which have transitive deps to old pkgs, we have to wait for now.
=> build(cargo): bump up dependencies

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml, packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture.rs, packages/transform-imports/transform/tests/fixture/regex/input.js, packages/transform-imports/transform/tests/fixture/regex/output.js, packages/transform-imports/transform/tests/fixture/simple/input.js, packages/transform-imports/transform/tests/fixture/simple/output.js
We are planning to move code to this repository to make maintenance easier.
But the license is a bit different - swc plugins are licensed under Apache 2.0 and have CLA (although I don't care about it.. I configured it just to avoid process like this)
So I'm asking the external contributors if they agree with moving the code.
Please leave a comment with `I agree` if you agree with these changes
---
cc
=> refactor(modularize-imports): Move code

Cargo.lock, crates/tailwind/Cargo.toml, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/tests/errors/nested-style-tags/output.stderr, packages/styled-jsx/transform/tests/errors/no-child/output.stderr, packages/styled-jsx/transform/tests/errors/two-children/output.stderr, packages/styled-jsx/transform/tests/errors/wrong-child-type/output.stderr, packages/styled-jsx/transform/tests/errors/wrong-jsx-expression-type/output.stderr, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
Bumps up latest swc_core to resolve circular dependency issue finally.
=> build(cargo): bump up swc_core

.github/workflows/bump-swc_core.yml
This PR trying to experiment automated action to create a PR to upgrade swc_* when new version is released. It is an action runs periodically (2 times a daily) which runs `cargo upgrade`, then create a PR if there's an update to be applied. If there is an open PR with specific branch name, it won't create new but trying to update PR with new commit when there's an update.
To create fully working pull request, action requires personal access token unfortunately. I choose name `GHA_UPGRADE_TOKEN` for those, having one under repository secrets will enable action to perform: 
We can use default `GITHUB_TOKEN` still, but it'll create PR with limited acesss with github-actions bot will not trigger any action to verify build is passing or not. (ref: …
=> ci(actions): trying to auto upgrade swc_*

packages/transform-imports/transform/Cargo.toml
in the file `transform/tests/fixture.rs`, we use the ecma::parser relative methods, but not define dependencies, causing error with `cargo test`.
```
use swc_core::{
ecma::parser::{EsConfig, Syntax},
ecma::transforms::testing::{test_fixture, FixtureTestConfig},
};
```
=> feat: add ecma_parser deps

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/emotion/transform/src/lib.rs, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
Before:
```
styled.div`
// color: red;
width: 100px;
`
```
will be minified to 
```
styled.div()("//color:red;width:100px")
```
the invalid comment will break the whole styles after that
=> fix: remove invalid single line comment

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/emotion/transform/src/lib.rs, packages/emotion/transform/tests/fixture.rs, packages/emotion/transform/tests/labels/filename-local/output.js, packages/emotion/transform/tests/labels/filename/output.js, packages/emotion/transform/tests/labels/input.tsx, packages/emotion/transform/tests/labels/local/output.js, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
Currently the filename is taken with the extension, but this should be excluded.
Fixes #153
=> fix(emotion): Autolabel filename label generation

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/emotion/transform/src/lib.rs, packages/emotion/transform/tests/fixture.rs, packages/emotion/transform/tests/labels/dirname-filename-local/output.js, packages/emotion/transform/tests/labels/dirname/output.js, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
The current documentation and original emotion babel plugin documentation specify using `[dirname]` as a label token, however, the current implementation uses `[dir]`. I also found a case when testing where the parent would be selected with the remainder of the path if a full path was provided.
Resolve both of these, and add additional fixtures to test the output.
=> fix(emotion): Autolabel dir vs dirname, ensure dirname is used over path

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/relay/src/lib.rs, packages/relay/transform/Cargo.toml, packages/relay/transform/src/lib.rs, packages/relay/transform/tests/fixture.rs, packages/relay/types.d.ts, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
This applies https://github.com/vercel/next.js/pull/43116
@orionmiz Are you fine with applying the patch to `swc-project/plugins`? The repositories of the swc-project GitHub organization have CLA, unlike next.js.
(CLA exists only to skip steps like this...)
=> feat(relay): Port patches from next.js repo

Cargo.lock, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/relay/package.json, packages/relay/src/lib.rs, packages/relay/transform/Cargo.toml, packages/relay/transform/src/lib.rs, packages/relay/transform/tests/fixture.rs, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
This PR expands `relay` plugin to pass mark for injecting new module imports. 
Unfortunately this makes interface (`relay`) breaking - maybe expose `Relay` struct itself as public and make it manually constructable would be the way to avoid breaking changes.
=> feat(relay): support unresolved mark

Cargo.lock, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/Cargo.toml, packages/jest/package.json, packages/loadable-components/Cargo.toml, packages/loadable-components/package.json, packages/noop/Cargo.toml, packages/noop/package.json, packages/relay/Cargo.toml, packages/relay/package.json, packages/relay/transform/Cargo.toml, packages/styled-components/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/tests/fixture/styles/output.js, packages/transform-imports/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml, packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture.rs, packages/transform-imports/transform/tests/fixture/mapping/input.js, packages/transform-imports/transform/tests/fixture/mapping/output.js
Currently, we only have one `transform: '...'` rule applied to all import names of a module import declaration. This implies that all exports of that module will follow the same rule, which is usually not the case.
Here're examples of some popular libraries:
- [lucide-react](https://unpkg.com/browse/lucide-react@0.252.0/dist/esm/lucide-react.js): `Accessibility`, `AccessibilityIcon` and `LucideAccessibility` all map to `'/icons/accessibility'`
- [react-bootstrap](https://unpkg.com/browse/react-bootstrap@2.8.0/esm/index.js): special case for `useAccordionButton`
- [@mui/material](https://unpkg.com/browse/@mui/material@5.14.1/index.js): `export *` expressions
To solve these problems, the original Babel plugin [supports using a function as the …
=> feat(transform-imports): Support mapping rules for individual import names

Cargo.lock, packages/constify/package.json, packages/constify/transform/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/Cargo.toml, packages/jest/package.json, packages/loadable-components/package.json, packages/noop/package.json, packages/react-remove-properties/package.json, packages/react-remove-properties/transform/Cargo.toml, packages/relay/README.md, packages/relay/package.json, packages/relay/src/lib.rs, packages/relay/transform/Cargo.toml, packages/relay/transform/src/lib.rs, packages/relay/transform/tests/fixture.rs, packages/relay/transform/tests/fixture/outputFileExtension/javascript/input.js, packages/relay/transform/tests/fixture/outputFileExtension/javascript/output.js, packages/relay/transform/tests/fixture/outputFileExtension/typescript/input.js, packages/relay/transform/tests/fixture/outputFileExtension/typescript/output.js, packages/remove-console/package.json, packages/remove-console/transform/Cargo.toml, packages/styled-components/package.json, packages/styled-components/transform/Cargo.toml, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/swc-magic/package.json, packages/swc-magic/transform/Cargo.toml, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml
In this PR we add `outputFileExtension` parameter in the config that can be:
- `ts`
- `js`
- `undefined`
When it's undefined we do the same behaviour as now which is controlled by `language` parameter
When it's configured we use the `outputFileExtension` parameter to specify which extension to use in the transpiled path import 
Example of usage: 
```typescript
[
'@swc/plugin-relay',
{
rootDir: __dirname,
artifactDirectory: './src/relay/__generated__',
eagerEsModules: true,
outputFileExtension: 'js'
},
],
```
We are migrating from `babel` to `swc` and currently our babel plugin 
The output in dist are javascript esm and instead of having this
```javascript
import __stuffFragment1 from "../../../relay/__generated__/stuffFragment.graphql";
import { graphql } from "react-relay";
export const …
```
=>  feat(relay): Add `outputFileExtension` option

packages/styled-components/transform/src/visitors/transpile_css_prop/transpile.rs, packages/styled-components/transform/tests/fixtures/transpile-css-prop/code.js, packages/styled-components/transform/tests/fixtures/transpile-css-prop/output.js
This fixes local identifiers are not handled properly in styled-components tagged literal.
```jsx
const id = (x) => x
const colorMap = {
orange: '#E3750E',
blue: '#38699F',
green: '#3F9348',
}
const Colored = (color, text) => {
return (
<div
css={css`
/* ${color} */ 
color: ${colorMap[color]};
background-color: ${id(color)};
`}
>
{text}
</div>
)
}
```
Local variable `color` is referenced outside the function.
```jsx
import _styled from "styled-components";
const id = (x)=>x;
const colorMap = {
orange: '#E3750E',
blue: '#38699F',
green: '#3F9348'
};
const Colored = (color, text)=>{
return <_StyledDiv $_css={color} $_css2={id(color)}>
{text}
</_StyledDiv>;
};
var _StyledDiv = _styled("div")`
/* ${(p)=>p.$_css} */ 
color: ${colorMap[color]};
background-color: ${(p)=>p.$_css2};
`;
```
```jsx …
```
=> fix(styled-components): handle `topLevelIdent[localIdent]` in template literal

.changeset/tidy-baboons-allow.md, Cargo.lock, packages/emotion/CHANGELOG.md, packages/emotion/Cargo.toml, packages/emotion/package.json, packages/emotion/transform/src/lib.rs
Follow up to #245 
Fixes this panic by ensuring that there is something to unwrap:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/plugins/plugins/packages/emotion/transform/src/lib.rs:449:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.270.26/src/plugin.rs:162:14:
failed to invoke plugin: failed to invoke plugin on 'Some("/Users/alexmiller/dev/app/node_modules/jest-runner/build/index.js")'
Caused by:
0: failed to invoke `@swc/plugin-emotion` as js transform plugin at @swc/plugin-emotion
1: RuntimeError: unreachable
Stack backtrace:
0: _napi_register_module_v1
1: …
```
=> fix(emotion): Fix panic on function name identifier being `None`

.changeset/thick-apricots-punch.md, packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture.rs, packages/transform-imports/transform/tests/fixture/default/input.js, packages/transform-imports/transform/tests/fixture/default/output.js, packages/transform-imports/transform/tests/fixture/mixed-default/input.js, packages/transform-imports/transform/tests/fixture/mixed-default/output.js, packages/transform-imports/transform/tests/fixture/namespace-export/input.js, packages/transform-imports/transform/tests/fixture/namespace-export/output.js, packages/transform-imports/transform/tests/fixture/namespace/input.js, packages/transform-imports/transform/tests/fixture/namespace/output.js
Closes https://github.com/swc-project/plugins/issues/323
This pull request adds support for namespace exports, and default and namespace imports, which were previously not supported by the plugin.
=> feat(transform-imports): Support all kinds of imports/exports

.changeset/funny-wasps-pay.md, packages/emotion/transform/src/lib.rs
[Currently](https://github.com/swc-project/plugins/issues/327), when `@swc/plugin-emotion` is used on Windows, it produces invalid CSS class names. Apparently this is an [unsolved issue for Rust](https://github.com/rust-lang/rust/issues/66621). In this PR I've updated the calculation of the `[filename]` `labelFormat` such that it handles both the Windows path, which includes the full path to the file, including backslashes, and the Unix path (which was working fine to begin with).
I have set up a [minimal repo](https://github.com/iryan2/cra-swc-emotion) for reproducing the issue and verifying the fix. The issue can be reproduced on [the `main` branch](https://github.com/iryan2/cra-swc-emotion), and the fix can be verified on [the `fix` …
=> fix(emotion): Strip backslashed segments for Windows path

.changeset/early-queens-help.md, Cargo.lock, packages/emotion/transform/src/lib.rs, packages/transform-imports/CHANGELOG.md, packages/transform-imports/README.md, packages/transform-imports/package.json, packages/transform-imports/transform/Cargo.toml, packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture.rs
Inverts https://github.com/swc-project/plugins/pull/324 as it caused some problems for next.js
=> fix(transform-imports): FIx default behavior

packages/transform-imports/transform/src/lib.rs, packages/transform-imports/transform/tests/fixture/side-effect-imports/input.js, packages/transform-imports/transform/tests/fixture/side-effect-imports/output.js
Closes https://github.com/swc-project/plugins/issues/329
=> fix(transform-imports): Preserve side-effect imports

.changeset/quick-seas-fold.md, packages/formatjs/transform/src/lib.rs
fix #395 
The original code contains some questionable choices for the case that the directory is missing which are replicated here for compatibility.
=> feat(formatjs): Support `idInterpolationPattern` placeholder

.changeset/pink-seas-fail.md, Cargo.lock, packages/styled-jsx/CHANGELOG.md, packages/styled-jsx/README.md, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/src/transform_css_swc.rs, packages/styled-jsx/transform/tests/fixture/legacy-nesting/input.js, packages/styled-jsx/transform/tests/fixture/legacy-nesting/output.lightningcss.js, packages/styled-jsx/transform/tests/fixture/legacy-nesting/output.swc.js
I'm not sure if allowing non-standard stuff is a good idea. But I'm creating this PR for compatibility with the Babel version styled-jsx...
=> refactor(styled-jsx): Allow legacy nesting syntax

packages/styled-components/transform/src/visitors/transpile_css_prop/transpile.rs
ClassCase will singularize the input (remove any trailing "s", e.g. "Icons" -> "Icon".) This doesn't match what babel-plugin-styled-components does.
=> fix(styled-components): Use PascalCase instead of ClassCase

packages/styled-components/transform/src/visitors/display_name_and_id.rs, packages/styled-components/transform/tests/fixtures/add-display-names-with-member-expressions/code.js, packages/styled-components/transform/tests/fixtures/add-display-names-with-member-expressions/config.json, packages/styled-components/transform/tests/fixtures/add-display-names-with-member-expressions/output.js
Resolves #420. 
This matches how babel-plugin-styled-components does it. (see [getName.js](https://github.com/styled-components/babel-plugin-styled-components/blob/4e2eb388d9c90f2921c306c760657d059d01a518/src/utils/getName.js#L39-L42)).
=> fix(styled-components): Visit member expressions for display name

packages/formatjs/__tests__/wasm.test.ts, packages/formatjs/transform/src/lib.rs
To bring parity with `ts-transformer` [implementation](https://github.com/formatjs/formatjs/blob/946a73c2f3bc51464298e40a85e8335e17304b3e/packages/ts-transformer/src/transform.ts#L415) and when the description is an object, stringify it
=> formatjs plugin - Serialize description objects

.changeset/tired-streets-grab.md, Cargo.lock, packages/formatjs/__tests__/wasm.test.ts, packages/formatjs/transform/Cargo.toml, packages/formatjs/transform/src/lib.rs
FormatJs Babel plugin allows using any binary-to-text encoding supported by NodeJS Buffer. Currently, this includes "base64", "base64url", and "hex". See <https://nodejs.org/api/buffer.html#buffers-and-character-encodings>.
Add support for "hex" and "base64url" encodings. Use "hex" by default to match the behavior of the Babel plugin.
fixes #401
=> feat(formatjs): Support hash encodings in id interpolation pattern

.changeset/happy-hotels-complain.md, packages/formatjs/__tests__/wasm.test.ts, packages/formatjs/transform/src/lib.rs
In my previous [PR](https://github.com/swc-project/plugins/pull/439) I missed the case that two description objects having the same keys but in a different order.
This will address that. Added a unit test to make sure it works.
=> fix(formatjs): sort description objects before serialization

packages/emotion/.npmignore, packages/formatjs/.npmignore, packages/jest/.npmignore, packages/loadable-components/.npmignore, packages/noop/.npmignore, packages/prefresh/.npmignore, packages/react-remove-properties/.npmignore, packages/relay/.npmignore, packages/remove-console/.npmignore, packages/styled-components/.npmignore, packages/styled-jsx/.npmignore, packages/swc-confidential/.npmignore, packages/swc-magic/.npmignore, packages/swc-sdk/.npmignore, packages/transform-imports/.npmignore
I noticed that the test files are still included in the published npm package at, e.g. https://www.npmjs.com/package/@swc/plugin-relay?activeTab=code
I'm assuming that's a typo.
Additionally, I added Cargo.toml to the .npmignore to help avoid conflicts with multi-language projects since Cargo can read into node_modules, e.g. https://github.com/bazelbuild/rules_rust/issues/3425
=> Fix tests typo, add Cargo.toml to .npmignore

.changeset/nine-kiwis-add.md, packages/formatjs/__tests__/wasm.test.ts, packages/formatjs/transform/src/lib.rs
In this PR we keep track of variable binding on declaration and assignments to get actual description values from.
The main motivator for this work is to support react compiler out of box and for it to support same id generation.
React compiler changes following code from:
```
export function Greeting() {
return (
<FormattedMessage
defaultMessage="Hello {name}"
description={{
text: "Hello",
img: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
}}
values={{
name: value.value,
}}
/>
);
}
```
to
```
export function Client(t0) {
const $ = _c(3);
const { value } = t0;
let t1;
if ($[0] === Symbol.for("react.memo_cache_sentinel")) {
t1 = {
text: "Hello",
img: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
};
$[0] = t1;
} …
```
=> fix(formatjs): Generate same id after React Compiler

.changeset/red-cows-add.md, Cargo.lock, packages/styled-jsx/CHANGELOG.md, packages/styled-jsx/README.md, packages/styled-jsx/__tests__/__snapshots__/wasm.test.ts.snap, packages/styled-jsx/package.json, packages/styled-jsx/transform/Cargo.toml, packages/styled-jsx/transform/src/transform_css_lightningcss.rs, packages/styled-jsx/transform/tests/fixture/svg-strip/input.js, packages/styled-jsx/transform/tests/fixture/svg-strip/output.lightningcss.js, packages/styled-jsx/transform/tests/fixture/svg-strip/output.swc.js, packages/styled-jsx/transform/tests/fixture/tpl-escape-2/output.lightningcss.js
The Babel CSS output for 
```js
const CUTOUT_AVATAR_PERCENTAGE_VISIBLE = Math.random();
const HEAD_MARGIN_PERCENTAGE = Math.random();
const MaskedDivBad = () => {
return (
<>
<div className="head">
<div className="avatar-wrapper" />
</div>
<style jsx>{`
.head {
position: relative;
}
.avatar-wrapper {
width: 40px;
height: 40px;
background: #ff6b6b;
border-radius: 50%;
mask-image:
url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><circle r="0.5" cx="0.5" cy="0.5"/></svg>'),
url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><circle r="${0.5 +
HEAD_MARGIN_PERCENTAGE}" cx="${0.5 +
CUTOUT_AVATAR_PERCENTAGE_VISIBLE +
HEAD_MARGIN_PERCENTAGE}" cy="0.5"/></svg>');
mask-size: 100% 100%;
mask-repeat: no-repeat;
mask-position: center; …
```
=> fix(styled-jsx): Fix SVG interpolation

.changeset/honest-walls-smile.md, packages/formatjs/__tests__/__snapshots__/wasm.test.ts.snap, packages/formatjs/__tests__/wasm.test.ts, packages/formatjs/transform/src/lib.rs
- Ensure messages in function calls and JSX are transformed to AST format when the ast option is set.
- Update tests and snapshots to reflect the correct AST output.
Fixes #497
Fixes an issue where messages were not being transformed to AST format when the ast option was enabled.
Now, both function calls and JSX components correctly output the defaultMessage as an AST when requested.
Also added a snapshot test for both `defineMessage`, `formatMessage` and `FormattedMessage`.
=> fix(formatjs): Fix ast tansform in jsx

.changeset/rotten-lions-smell.md, packages/formatjs/__tests__/wasm.test.ts, packages/formatjs/transform/src/lib.rs
I made a fix that correctly handles the extraction of descriptions wrapped in template string literals. The current behavior was resulting in the generation of an incorrect identifier. This pull request fixes this issue.
```jsx
// source
<FormattedMessage
defaultMessage="Hello, World!"
description="Greeting message"
/>
<FormattedMessage
defaultMessage="Hello, World!"
description={`Greeting message`}
/>
// transformed
_jsx(FormattedMessage, {
id: "Ae/S0P"
});
_jsx(FormattedMessage, {
id: "N015Sp",
description: "Greeting message"
});
```
=> fix(formatjs): Fix description extract for the template literal string

packages/formatjs/transform/src/lib.rs
- enable `requires_other_clause` and `should_parse_skeletons` by default
- follow default behavior of `@formatjs/icu-messageformat-parser`
ref: https://github.com/formatjs/formatjs/blob/e11b9b57a5ed745584b169c13b0a1812ba9e6051/packages/icu-messageformat-parser/index.ts#L41-L42
=> fix(formatjs): Use default parser options
